function renderTracker(){
  if(!$('individualTracker')) return;
  const teams=[...new Set(people.filter(p=>p.type==='Swarm'&&p.team).map(p=>p.team))].sort();
  const sel=$('trackerTeam'); if(sel){const cur=sel.value; sel.innerHTML='<option value="all">All Teams</option>'+teams.map(t=>`<option value="${t}">${t}</option>`).join(''); sel.value=teams.includes(cur)?cur:'all';}
  const type=$('trackerType')?.value||'all', team=$('trackerTeam')?.value||'all', q=($('trackerSearch')?.value||'').toLowerCase();
  const filtered=people.filter(p=>(type==='all'||p.type===type)&&(team==='all'||p.team===team)&&(`${p.name} ${p.team} ${p.session}`.toLowerCase().includes(q)));
  $('trackRecords').textContent=attendanceHistory.length; $('trackTeams').textContent=teams.length; $('trackSwarmToday').textContent=people.filter(p=>p.type==='Swarm'&&p.checked).length; $('trackPublicToday').textContent=people.filter(p=>p.type==='Public'&&p.checked).length;
  $('individualTracker').innerHTML=`<table><tr><th>Player</th><th>Type</th><th>Team</th><th>Classes Attended</th><th>Today</th><th>Last Attended</th><th>History</th></tr>${filtered.map(p=>{let h=attendanceFor(p).sort((a,b)=>a.date.localeCompare(b.date));let last=h[h.length-1]?.date||'';let dates=h.slice(-8).map(r=>r.date.slice(5)).join(' · ');return `<tr><td>${p.name}</td><td>${p.type}</td><td>${p.team||''}</td><td>${h.length}</td><td>${p.checked?'Yes':'No'}</td><td>${last}</td><td>${dates}</td></tr>`}).join('')}</table>`;
  const teamRows=teams.map(t=>{let roster=people.filter(p=>p.type==='Swarm'&&p.team===t);let today=roster.filter(p=>p.checked).length;let totalRecords=attendanceHistory.filter(r=>r.type==='Swarm'&&r.team===t).length;let pct=roster.length?Math.round(today/roster.length*100):0;return {team:t,roster:roster.length,today,totalRecords,pct};});
  $('teamTracker').innerHTML=`<table><tr><th>Team</th><th>Roster Loaded</th><th>Attended Today</th><th>Today %</th><th>Total Skills Records</th></tr>${teamRows.map(r=>`<tr><td>${r.team}</td><td>${r.roster}</td><td>${r.today}</td><td>${r.pct}%</td><td>${r.totalRecords}</td></tr>`).join('')}</table>`;
}
function exportHistory(){let header=['Date','Activity','Activity Type','Name','Type','Team','Session','Homework','Waiver','QR ID'];let csv=[header.join(',')].concat(attendanceHistory.map(r=>[r.date,r.activity,r.activityType,r.name,r.type,r.team,r.session,r.homework,r.waiver,r.id].map(x=>`"${(x||'').toString().replace(/"/g,'""')}"`).join(','))).join('\n');downloadCsv(csv,`mss-attendance-history-${todayKey()}.csv`);}
function exportTeamReport(){let teams=[...new Set(people.filter(p=>p.type==='Swarm'&&p.team).map(p=>p.team))].sort();let rows=[];teams.forEach(t=>people.filter(p=>p.type==='Swarm'&&p.team===t).forEach(p=>{let h=attendanceFor(p);rows.push([t,p.name,p.checked?'Yes':'No',h.length,h[h.length-1]?.date||'',p.email,p.phone]);}));let header=['Team','Player','Attended Today','Total Classes Attended','Last Attended','Parent Email','Parent Phone'];let csv=[header.join(',')].concat(rows.map(r=>r.map(x=>`"${(x||'').toString().replace(/"/g,'""')}"`).join(','))).join('\n');downloadCsv(csv,`swarm-team-skills-attendance-${todayKey()}.csv`);}
async function copyTeamReport(){let teams=[...new Set(people.filter(p=>p.type==='Swarm'&&p.team).map(p=>p.team))].sort();let txt=teams.map(t=>{let roster=people.filter(p=>p.type==='Swarm'&&p.team===t);let today=roster.filter(p=>p.checked).length;return `${t}: ${today}/${roster.length} attended skills today (${roster.length?Math.round(today/roster.length*100):0}%)`;}).join('\n'); if(!txt) txt='No Swarm teams loaded.'; await navigator.clipboard.writeText(txt); alert('Copied team summary.');}
function downloadCsv(csv,filename){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=filename;a.click();}
function importHistory(){let input=$('historyFile'); if(!input.files[0]) return alert('Choose a history CSV first.'); let reader=new FileReader(); reader.onload=e=>{let rows=parseCSV(e.target.result);let imported=rows.map(r=>({date:key(r,['Date'])||todayKey(),activity:key(r,['Activity']),activityType:key(r,['Activity Type']),name:key(r,['Name']),type:key(r,['Type']),team:key(r,['Team']),session:key(r,['Session']),homework:key(r,['Homework'])||key(r,['Homework Complete']),waiver:key(r,['Waiver'])||key(r,['Waiver Complete']),id:key(r,['QR ID','ID'])})).filter(r=>r.name); attendanceHistory=[...attendanceHistory,...imported]; save(); render(); alert(`Imported ${imported.length} attendance history records.`);}; reader.readAsText(input.files[0]);}
function saveSettings(){settings={name:$('activityName').value,type:$('activityType').value,paid:$('rulePaid').checked,waiver:$('ruleWaiver').checked,homework:$('ruleHomework').checked};save();render();}
