function setupTabs(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden');renderAll();});}
function applySettingsToUI(){ $('activityTitle').textContent=settings.activityName; $('datePill').textContent=new Date().toLocaleDateString([], {weekday:'short',month:'short',day:'numeric'}); $('setActivityName').value=settings.activityName; $('setActivityType').value=settings.activityType; $('setSession1').value=settings.sessions[0]||''; $('setSession2').value=settings.sessions[1]||''; ['srcPublic','srcSwarm','methodQR','methodMembership','methodManual','ruleWaiver','ruleWaiverPublic','ruleWaiverSwarm','ruleHomework','ruleArrival','ruleSwarmEligible'].forEach(id=>{if($(id)) $(id).checked=!!settings[id];}); $('scanPanel').classList.toggle('hidden',!(settings.methodQR||settings.methodMembership)); const sf=$('sessionFilter'); const old=sf.value; sf.innerHTML='<option value="all">All Sessions</option>'+settings.sessions.filter(Boolean).map(s=>`<option>${s}</option>`).join('')+'<option>Eligible Any Session</option>'; if([...sf.options].some(o=>o.value===old))sf.value=old;}
function saveSettings(){settings.activityName=clean($('setActivityName').value)||'MSS Attendance';settings.activityType=$('setActivityType').value;settings.sessions=[$('setSession1').value,$('setSession2').value].map(clean).filter(Boolean);['srcPublic','srcSwarm','methodQR','methodMembership','methodManual','ruleWaiver','ruleWaiverPublic','ruleWaiverSwarm','ruleHomework','ruleArrival','ruleSwarmEligible'].forEach(id=>settings[id]=!!$(id).checked);save();applySettingsToUI();renderAll();alert('Setup saved.');}
function resetSettings(){localStorage.removeItem(LS+'settings');location.reload();}
function personCard(p){const needs=needsWaiver(p);return `<div class="person ${p.checked?'checked':''} ${needs?'blocked':''}"><div class="name">${p.name||'(No name)'}</div><div class="meta">${p.type}${p.team?' • '+p.team:''}${p.session?' • '+p.session:''}</div><div class="badges"><span class="badge ${p.type==='Swarm'?'swarm':'public'}">${p.type}</span>${p.checked?`<span class="badge good">Checked ${p.arrival||''}</span>`:'<span class="badge neutral">Not checked</span>'}${!requiresWaiver(p)?'<span class="badge neutral">Waiver Not Required</span>':(p.waiver?'<span class="badge good">Waiver</span>':'<span class="badge warn">Needs Waiver</span>')}${p.homework?'<span class="badge good">Homework</span>':''}${p.type==='Swarm'?'<span class="badge swarm">Skills Eligible</span>':''}</div><div class="small">Parent: ${p.parent||'—'}<br>Email: ${p.email||'—'}<br>Phone: ${p.phone||'—'}</div><div class="row" style="margin-top:10px"><button class="btn ${p.checked?'secondary':'green'}" onclick="toggleCheck('${p.id}')">${p.checked?'Undo':'Check In'}</button><button class="btn secondary" onclick="toggleHomework('${p.id}')">Homework</button><button class="btn secondary" onclick="startWaiver('${p.id}')">Waiver</button></div></div>`}
function renderPeople(){const v=visiblePeople();$('peopleList').innerHTML=v.map(personCard).join('')||'';$('filterMsg').classList.toggle('hidden',!!v.length||!people.length);$('filterMsg').textContent=people.length?'No participants match the current filters. Try Clear Filters.':'No participants loaded yet.';}
function renderKpis(){ $('kRegistered').textContent=people.length; $('kChecked').textContent=people.filter(p=>p.checked).length; $('kWaiver').textContent=people.filter(p=>needsWaiver(p)).length; $('kHomework').textContent=people.filter(p=>p.homework).length;}
function renderTables(){const rows=people.slice(0,300).map(p=>`<tr><td>${p.name}</td><td>${p.type}</td><td>${p.team||''}</td><td>${p.session||''}</td><td>${p.email||''}</td><td>${p.phone||''}</td></tr>`).join('');$('importTable').innerHTML=`<table><tr><th>Name</th><th>Type</th><th>Team</th><th>Session</th><th>Email</th><th>Phone</th></tr>${rows}</table>`;$('waiverTable').innerHTML=`<table><tr><th>Name</th><th>Type</th><th>Status</th><th>Action</th></tr>${people.map(p=>`<tr><td>${p.name}</td><td>${p.type}</td><td>${!requiresWaiver(p)?'Not Required':(p.waiver?'Complete':'Missing')}</td><td><button class="btn secondary" onclick="startWaiver('${p.id}')">Open</button></td></tr>`).join('')}</table>`;$('homeworkTable').innerHTML=`<table><tr><th>Name</th><th>Type</th><th>Team</th><th>Homework</th><th>Action</th></tr>${people.map(p=>`<tr><td>${p.name}</td><td>${p.type}</td><td>${p.team}</td><td>${p.homework?'Complete':'Pending'}</td><td><button class="btn secondary" onclick="toggleHomework('${p.id}')">Toggle</button></td></tr>`).join('')}</table>`;}
function clearFilters(){$('sessionFilter').value='all';$('typeFilter').value='all';$('statusFilter').value='all';$('search').value='';renderAll();}
function renderAll(){applySettingsToUI();renderKpis();renderPeople();renderTables();renderComm();renderTracker();renderReports();}
